services:
  - name: gym-management-backend
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: (Paste the content of your JSON file here as a single line string if not using Render dashboard UI)
